language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  fast_finish: true

install:
  - travis_retry composer update $COMPOSER_OPTS

script:
  - bin/phpunit --coverage-text --coverage-clover coverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
