language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_OPTS

script:
  - mkdir -p build/logs
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs src --standard=psr2 -sp

after_script:
  - php vendor/bin/coveralls

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/6e5e2dea76dada46bf9d'
    on_success: change
    on_failure: always
    on_start: never
