language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm-3.12
      sudo: required
      dist: trusty
      group: edge
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-stable --prefer-lowest"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_OPTS

script: composer test

after_script:
  - php vendor/bin/coveralls

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/6e5e2dea76dada46bf9d'
    on_success: change
    on_failure: always
    on_start: never
