---
after_success:
  - "./vendor/bin/phpunit --coverage-clover=coverage.xml"
  - "bash < (curl -s https://codecov.io/bash)"
before_install:
  - "travis_retry composer self-update"
  - "travis_retry composer clear-cache"
env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"
install:
  - "if [[ \"$DEPENDENCIES\" = 'high' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable; fi"
  - "if [[ \"$DEPENDENCIES\" = 'low' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable --prefer-lowest; fi"
language: php
php:
  - 7.0
  - 7.0snapshot
  - 7.1
  - 7.1snapshot
  - master
  - hhvm
script:
  - "./vendor/bin/grumphp run"
sudo: false
