language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source --prefer-lowest

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
